export enum CallState {
	RINGING = "RINGING",
	HANGUP = "HANGUP",
	ESTABLISHED = "ESTABLISHED",
	FINISHED = "FINISHED",
	MISSED = "MISSED",
	BUSY = "BUSY",
	NOTFOUND = "NOTFOUND",
	REJECTED = "REJECTED",
	CANCEL = "CANCEL",
	TRANSFERRED = "TRANSFERRED",
	REJECTED_OPENING_HOURS = "REJECTED_OPENING_HOURS"
}
